---
title: "Fairness"
author: "Gizelle H"
date: "11/07/2020"
output: html_document
---

# Fairness in Trauma Prediction Models

## Introduction

Trauma continues to be a major contributor to the global burden of
disease - an estimated 520 million injuries required health
interventions in 2017 alone ^(1)^ Annually, nearly 4.5 million people
die due to trauma and over 90% of these deaths occur in low- and
middle-income countries ^(2)^.

<!-- Okay, replace the next paragraph with a paragraph on trauma
mortality prediction models. What they are and why they are
used. Mention: "such as the Kampala Trauma Score (KTS), Revised Trauma
Score (RTS), Trauma and Injury Severity Score (TRISS), A Severity
Characterization Of Trauma (ASCOT) and Base deficit and Injury
Severity Score (BISS)"-->

With an expected increase in trauma globally ^(3)^, it is imperative
that holistic trauma care is guided also by gender and health economic
considerations ^(4)^. A way to improve those could be development of
more inclusive prediction models that would inform better clinical
judgement and ensure quality research and revision. <!-- Remove this
paragraph -->

Deaths from trauma are disproportionately distributed between men and
women. Road traffic injury related deaths occur almost three times as
much in men than in women whereas burn injury related deaths occur
more in women ^(3)^. This disproportionality can be attributed to
increased incidences of interpersonal violence in men ^(5)^, and women
seeking delayed medical care ^(6)^. <!-- I think you can remove this
as well -->

Trauma databases include more men than women ^(9,10)^, and most trauma
severity scores were developed in overwhelmingly male populations
^(11,12)^. The effect of this inherent bias on the fairness
(distribution of model errors), have not been previously studied
despite potentially affecting the quality of care provided to women.

The study of fairness in trauma prediction models can help identify
and correct potential flaws in these models and improve trauma
outcomes by informing better treatment protocols. The aim of this
study is to assess and compare the fairness of various trauma
prediction models.<!-- The first part of this paragraph may fit better
in Discussion later, but let's keep it here for now -->

## References <!-- Move this to last in the document -->

1. 	James SL, Abate D, Abate KH, Abay SM, Abbafati C, Abbasi N, et al. Global, regional, and national incidence, prevalence, and years lived with disability for 354 Diseases and Injuries for 195 countries and territories, 1990-2017: A systematic analysis for the Global Burden of Disease Study 2017. Lancet. 2018;392(10159):1789–858. 
2. 	Roth GA, Abate D, Abate KH, Abay SM, Abbafati C, Abbasi N, et al. Global, regional, and national age-sex-specific mortality for 282 causes of death in 195 countries and territories, 1980–2017: a systematic analysis for the Global Burden of Disease Study 2017. Lancet. 2018;392(10159):1736–88. 
3. 	Who. Injuries and Violence: The Facts. Geneva, Switz WHO [Internet]. 2010;2–18. Available from: http://scholar.google.com/scholar?hl=en&btnG=Search&q=intitle:Injuries+and+Violence:+The+Facts#0
4. 	Shaw LJ, Pepine CJ, Xie J, Mehta PK, Morris AA, Dickert NW, et al. Quality and Equitable Health Care Gaps for Women: Attributions to Sex Differences in Cardiovascular Medicine. J Am Coll Cardiol. 2017;70(3):373–88. 
5. 	Tingne CV, Shrigiriwar MB, Ghormade PS, Kumar NB. Quantitative analysis of injury characteristics in victims of interpersonal violence: An emergency department perspective. J Forensic Leg Med [Internet]. 2014;26(70):19–23. Available from: http://dx.doi.org/10.1016/j.jflm.2014.06.003
6. 	Tenenbaum A, Nordeman L, Sunnerhagen KS, Gunnarsson R. Gender differences in care-seeking behavior and healthcare consumption immediately after whiplash trauma. PLoS One. 2017;12(4):1–9. 
7. 	Sharpe JP, Magnotti LJ, Weinberg JA, Brocker JA, Schroeppel TJ, Zarzaur BL, et al. Gender disparity in ventilator-associated pneumonia following trauma: Identifying risk factors for mortality. J Trauma Acute Care Surg. 2014;77(1):161–5. 
8. 	Pape M, Giannakópoulos GF, Zuidema WP, De Lange-Klerk ESM, Toor EJ, Edwards MJR, et al. Is there an association between female gender and outcome in severe trauma? A multi-center analysis in the Netherlands. Scand J Trauma Resusc Emerg Med. 2019;27(1):1–10. 
9. 	Haider AH, Crompton JG, Oyetunji T, Stevens KA, Efron DT, Kieninger AN, et al. Females have fewer complications and lower mortality following trauma than similarly injured males: A risk adjusted analysis of adults in the National Trauma Data Bank. Surgery [Internet]. 2009;146(2):308–15. Available from: http://dx.doi.org/10.1016/j.surg.2009.05.006
10. 	Meng R, Xu X, Xu Y, Luo C, Xu H, Wang Y, et al. Epidemiological characteristics of injury mortality in Guangdong Province, China, 2015. BMC Public Health. 2019;19(1):1–8. 
11. 	Akay S, Ozturk AM, Akay H. Comparison of modified Kampala trauma score with trauma mortality prediction model and trauma-injury severity score: A National Trauma Data Bank Study. Am J Emerg Med [Internet]. 2017;35(8):1056–9. Available from: http://dx.doi.org/10.1016/j.ajem.2017.02.035
12. 	Tohira H, Jacobs I, Mountain D, Gibson N, Yeo A. Systematic review of predictive performance of injury severity scoring tools. Scand J Trauma Resusc Emerg Med. 2012;20:1–12.  


> _Need better understanding of which statistical functions need to applied_
> _and what the parameters are for prediction model validation_


## Methods

### 1.1 Study design & data sources

Our study is a retrospective analysis of the anonymous multicentre
Towards Improved Trauma Care Outcomes (TITCO) in India cohort.

### 1.2 Key study dates

We conducted this analysis between [dates] based on data directly
observed or retrieved from patient records between July 2013 and
December 2015.

### 2.1 Study setting

The patient data was collected from four hospitals within urban,
Indian cities of Mumbai, New Delhi and Kolkata. This included two
tertiary care hospitals with dedicated trauma wards and one without,
while the fourth was a dedicated trauma centre.

### 2.2 Eligibility criteria

The TITCO cohort includes all patients presenting with trauma, alive
at the time of arrival, and who were admitted to the participating
hospitals, regardless of age or gender. Those dying between arrival
and admission were also included. The exclusion criteria were subjects
dead on arrival and those presenting exclusively with peripheral
injuries.

### 3.1 Predicted outcome

The predicted outcome is death following trauma with or without
surgical intervention, within 48 hours to 30 days from time of arrival
at the hospital.<!-- Why not before 48 hours? -->

### 3.2 Actions to blind outcome assessment

All data was collected based on standardized criteria regardless of
demographic details and outcomes, including all predefined predictors
as applicable.

### 4.1 Predictors and measurement
<!-- Read up on the models you mention in the introduction and check
which of those that can be calculated in the TITCO data. Then list the
variables included in those models in this section -->

-	Grouping trauma by anatomical regions based on the abbreviated
        injury scale (AIS).
-	Assigning an AIS grading to each primary injury and any secondary
        injuries – recorded via CT reports, x-ray findings, FAST findings,
        intraoperative diagnosis & physician notes.
-	Assigning standardized ICD-10 codes for nature of injury.
-	Assigning injury severity scores (ISS) and new injury severity
        scores (NISS) to all subjects based on the AIS.
-	Recording vital sign parameters at fixed time intervals for all patients.
-	Recording GCS scores at fixed time intervals for all patients.
-	Recording hemoglobin and hematocrit status on admission for all patients.

### 4.2 Actions to blind predictor assessment

-	Ensuring expert opinion in recording intraoperative diagnoses
        and assigning primary injury.
-	Following standardized coding methods (ICD-10)
-	Ensuring all coders receive similar standardized training
        for data collection. 
<!-- Not sure about this section, but let's keep it for now -->		

### 5. Sample size

<!-- Here we need to calculate if this is enough to detect a
difference in mean absolute prediction error between men and women
-->

```{r sample-size-calculation, echo = FALSE, include = FALSE}
## This is how you can mix text and code

## Let's use mean absolute prediction error (MAPE) as the study
## outcome. This is calculated as the mean absolute difference between
## the actual outcome (1 = died, 0 = survived) and the predicted
## probability of that outcome. So let's say a patient died with a
## probability of death of 0.8 (estimated by a model). Then the APE
## for this patient is 0.2. The mean of all APEs is MAPE. Because MAPE
## can be considered continuous we can use a t-test to compare MAPE
## between men and women. We can use a paired t-test to compare
## the difference in MAPE between men and women between two models.

library(pwr)

## Using 0.2 to represent a "small" effect size, see for example https://people.bath.ac.uk/pssiw/stats2/page2/page14/page14.html#:~:text=Cohen%20suggested%20that%20d%3D0.2,a%20'large'%20effect%20size.&text=Partial%20eta%2Dsquared%20isn't,most%20purposes%20and%20is%20publishable.
stats <- pwr.t.test(d = 0.2, power = 0.8, type = "two.sample", alternative = "two.sided")
stats.paired <- pwr.t.test(d = 0.2, power = 0.8, type = "paired", alternative = "two.sided")

```

The TITCO cohort includes 16,000 trauma patients admitted to the four
participating hospitals. We need at least `r stats$n` men and as
many women, coming to a minimum total sample size of `r stats$n*2`,
to detect an effect size of 0.2 (considered a small effect size [ADD
REF]) when comparing the mean absolute prediction error between men
and women for any model with 80% power and a significance level of 5%.

### 6. Missing data

We will perform a complete case analysis, meaning that patients with
missing values in any predictor or outcome will be excluded.

### 7.1 Predictor analysis

We will describe predictor values separately for men and women.<!-- No
need to test potential differences formally-->

### 7.2 Type of model and predictor selection

Prediction models for trauma mortality, based on anatomical
distribution of injuries and physiological variables were applied to
the dataset.<!-- See my comments on 4.1 --> Predictive value of site and
type of injury; changes in systolic blood pressure, heart rate & GCS
scores; differences in time of injury, time of arrival and first
surgical intervention was assessed and validated _[does the receiver
operating characteristics curve have a function here?]_

### 7.3 Measures used to assess and compare model performance

Standard error of means was calculated for analyzed variables and
compared across various predictive models applied to the dataset based
on gender differences<!-- See the sample size section for details on
the study outcome, revise accordingly -->. _[Mention ROCC?]_
